In [6]:
# ref: https://www.zhihu.com/question/456213566/answer/2518011810
import tensorflow as tf

rand_tensor = tf.random.normal(shape=[2, 2, 3])
sg_1 = tf.nn.softmax(rand_tensor, axis=0)
sg_2 = tf.nn.softmax(rand_tensor, axis=1)
sg_3 = tf.nn.softmax(rand_tensor, axis=2)

with tf.Session() as sess:
    rand_tensor, sg_1, sg_2, sg_3 = sess.run([rand_tensor, sg_1, sg_2, sg_3])
    print("rand_tensor:\n", rand_tensor)
    print("\n")
    print("sg_1:\n", sg_1)
    print("\n")
    print("sg_2:\n", sg_1)
    print("\n")
    print("sg_3:\n", sg_1)
    print("\n")

rand_tensor:
 [[[ 0.94916886  0.16764274  0.95155317]
  [ 1.1069479  -1.1047778   0.46299726]]

 [[ 0.38737515 -0.58832234 -1.3313001 ]
  [-0.18981606 -0.02731347 -1.0182445 ]]]


sg_1:
 [[[0.63686746 0.680477   0.907447  ]
  [0.7852898  0.25398618 0.81476   ]]

 [[0.36313254 0.31952292 0.09255303]
  [0.21471016 0.7460139  0.18523994]]]


sg_2:
 [[[0.63686746 0.680477   0.907447  ]
  [0.7852898  0.25398618 0.81476   ]]

 [[0.36313254 0.31952292 0.09255303]
  [0.21471016 0.7460139  0.18523994]]]


sg_3:
 [[[0.63686746 0.680477   0.907447  ]
  [0.7852898  0.25398618 0.81476   ]]

 [[0.36313254 0.31952292 0.09255303]
  [0.21471016 0.7460139  0.18523994]]]


