In [1]:
# 1）测试tf.tile
import tensorflow as tf
a = tf.constant([7,19])
a1 = tf.tile(a, multiples=[3]) # 第一个维度复制3遍, (1,2)=>(1,6)
b = tf.constant([[4,5], [3,5]])
b1 = tf.tile(b, multiples=[2,3]) # 第一个维度复制2遍，第二个维度复制3遍, (2,2)=>(4,6)

with tf.Session() as sess:
    a_out = sess.run(a)
    a1_out = sess.run(a1)
    b_out = sess.run(b)
    b1_out = sess.run(b1)
    print("a: ", a_out)
    print("a1: ", a1_out)
    print("b: ", b_out)
    print("b1: ", b1_out)

a:  [ 7 19]
a1:  [ 7 19  7 19  7 19]
b:  [[4 5]
 [3 5]]
b1:  [[4 5 4 5 4 5]
 [3 5 3 5 3 5]
 [4 5 4 5 4 5]
 [3 5 3 5 3 5]]


In [2]:
# 2) 测试 tf.expand_dims
import tensorflow as tf

t = tf.constant([7,19]) #shape: (2,)
e1 = tf.expand_dims(t,0).shape.as_list() # (1,2) # 第0维扩展
e2 = tf.expand_dims(t,1).shape.as_list() # (2,1) # 第1维扩展
e3 = tf.expand_dims(t,-1).shape.as_list() # (2,1)

t2 = tf.Variable(tf.ones([2,3,5], dtype=tf.float32)) #shape: (2,3,5)
e4 = tf.expand_dims(t2,0).shape.as_list() # (1,2,3,5) 
e5 = tf.expand_dims(t2,2).shape.as_list() # (2,3,1,5) 
e6 = tf.expand_dims(t2,3).shape.as_list() # (2,3,5,1)

print("e1~e6: \n{} \n{} \n{} \n{} \n{} \n{}".format(e1, e2, e3, e4, e5, e6))

e1~e6: 
[1, 2] 
[2, 1] 
[2, 1] 
[1, 2, 3, 5] 
[2, 3, 1, 5] 
[2, 3, 5, 1]


In [3]:
# 3) 测试 tf.squeeze
import tensorflow as tf 

t = tf.Variable(tf.ones([1,2,1,3,1,1]), dtype=tf.float32)
s0 = t.shape.as_list() # (1,2,1,3,1,1)
s1 = tf.squeeze(t).shape.as_list() # 去除所有维度的冗余dim => (2,3)
s2 = tf.squeeze(t, [2,4]).shape.as_list() # 去除2和4维度的1 => (1,2,3,1)

print("s0~s2: \n{} \n{} \n{}".format(s0, s1, s2))

s0~s2: 
[1, 2, 1, 3, 1, 1] 
[2, 3] 
[1, 2, 3, 1]
