In [1]:
# ref: 
# - https://cangmang.xyz/articles/tensorflow-data-type#TensorFlow-%E4%B8%AD%E7%9A%84%E5%BC%A0%E9%87%8F%E5%92%8C-Numpy-%E6%95%B0%E7%BB%84
# - https://cangmang.xyz/articles/tensorflow-constant-and-variable

import tensorflow as tf 
import numpy as np

# tf.constant 将python各种类型的常量转化为 tensor (直接定义)
py_v1 = 3.14  # python 内置数据类型：浮点数
py_v2 = 4  #
py_v3 = 'hello tf'
py_v4 = True
py_v5 = [[1,2,3], [4,5,6]]
tf_tensor_v1 = tf.constant(py_v1)  # 创建只含有一个元素的标量
tf_tensor_v2 = tf.constant(py_v2)
tf_tensor_v3 = tf.constant(py_v3)
tf_tensor_v4 = tf.constant(py_v4)
tf_tensor_v5 = tf.constant(py_v5)

# tf.Variable 从 Numpy/python 中构建 TensorFlow变量
n0 = np.array(20, dtype=np.int32)
n1 = np.array([b"Tensor", b"flow", b"is", b"great"])
n2 = np.array([[True, False, False], [False, True, False]], dtype=np.bool)
tensor0D = tf.Variable(n0, name="t_0")
tensor1D = tf.Variable(n1, name="t_1")
tensor2D = tf.Variable(n2, name="t_2")
tensor_py = tf.Variable([[1,2], [3,4]], name="tensor_py")

# tf.convert_to_tensor() 方法将 Python 列表或元祖转换为张量
a_list = list([1, 2, 3])  # 创建一个列表
b_tuple = (11.0, 22.2, 33)  # 创建一个元祖
c_str_tuple = ("a", "b", "c", "d")  # 创建一个字符串元祖
tensor_a = tf.convert_to_tensor(a_list, dtype=tf.float32)
tensor_b = tf.convert_to_tensor(b_tuple)
tensor_c = tf.convert_to_tensor(c_str_tuple)
tensor_add = tf.math.add(tensor_a, tensor_b)

# 数据类型转换 tf.cast
vec_actual = tf.constant([1, 1, 2, 0, 1])  # 假设为分类实际值
vec_pre = tf.constant([1, 0, 1, 0, 1])  # 假设为算法预测的分类值
acc_bool = vec_actual == vec_pre  # 判断预测是否准确
acc_float = tf.cast(acc_bool, tf.float32)  # 将布尔型转换成浮点型
acc_rate = tf.math.reduce_mean(acc_float)  # 计算平均值（平均值即为准确率）

# 字符串操作 more to TODO


with tf.Session() as sess:
    v1, v2, v3, v4, v5 = sess.run([tf_tensor_v1, tf_tensor_v2, tf_tensor_v3, tf_tensor_v4, tf_tensor_v5])
    print("tf_tensor_v1: ", v1)
    print("tf_tensor_v2: ", v2)
    print("tf_tensor_v3: ", v3)
    print("tf_tensor_v4: ", v4)
    print("tf_tensor_v5: ", v5)
    #
    print("=============")
    #
    print("tensor0D: {0}".format(tensor0D))
    print("tensor1D: {0}".format(tensor1D))
    print("tensor2D: {0}".format(tensor2D))
    print("tensor_py: {0}".format(tensor_py))
    #
    print("=============")
    #
    acc_rate = sess.run(acc_rate)
    print("acc_float type: ", acc_float)
    print("acc_rate: ", acc_rate)
    #
    print("=============")
    #
    print("tensor_a: {0}".format(tensor_a))
    print("tensor_b: {0}".format(tensor_b))
    print("tensor_c: {0}".format(tensor_c))
    print("tensor_add: {0}".format(tensor_add))

tf_tensor_v1:  3.14
tf_tensor_v2:  4
tf_tensor_v3:  b'hello tf'
tf_tensor_v4:  True
tf_tensor_v5:  [[1 2 3]
 [4 5 6]]
tensor0D: <tf.Variable 't_0:0' shape=() dtype=int32_ref>
tensor1D: <tf.Variable 't_1:0' shape=(4,) dtype=string_ref>
tensor2D: <tf.Variable 't_2:0' shape=(2, 3) dtype=bool_ref>
tensor_py: <tf.Variable 'tensor_py:0' shape=(2, 2) dtype=int32_ref>
acc_float type:  Tensor("Cast:0", shape=(), dtype=float32)
acc_rate:  0.0
tensor_a: Tensor("Const_5:0", shape=(3,), dtype=float32)
tensor_b: Tensor("Const_6:0", shape=(3,), dtype=float32)
tensor_c: Tensor("Const_7:0", shape=(4,), dtype=string)
tensor_add: Tensor("Add:0", shape=(3,), dtype=float32)


In [2]:
# ref
# - https://cangmang.xyz/articles/tensorflow-usual-tensor-created-methods

import tensorflow as tf 
import numpy as np

import tensorflow as tf

a = tf.zeros(5, dtype=tf.int32)  # 一维张量，数值类型为 int32
b = tf.zeros([2, 5], dtype=tf.int32)  # 二维张量，数值类型为 int32
c = tf.zeros((3, 3))  # 二维张量，数值类型为 float32

a_cons = tf.constant([[1, 2, 3.0], [4, 5, 6]]) # “就高不就低”原则，即张量的数据类型以最高精度的数值类型为准,
b_zero = tf.zeros_like(a_cons)  # 借用 a_cons 的类型和维度
c_zero = tf.zeros_like(a_cons, dtype=tf.int32)  # 修改数据类型为 int32

all_one = tf.ones([2, 3], dtype=tf.int32)
all_one_like = tf.ones_like(a_cons)

fill = tf.fill([2, 3], 6)  # 生成 2 行 3 列，且值为 6 的张量

rand = tf.random.normal(shape=[3, 2], mean=10, stddev=2, dtype=tf.float32)

uni_tensor = tf.random.uniform([2, 2])

range_a = tf.range(10) # 返回区间为 [0, 10)，步长为 1 的整数序列
range_b = tf.range(start=3, limit=18, delta=3) # 返回区间为 [3, 18)，步长为 3 的整数序列
range_c = tf.range(3, 18, 0.5) # 返回区间为 [3, 18)，步长为 0.5 的浮点数序列


with tf.Session() as sess:
    a,b,c, b_zero,c_zero, all_one,all_one_like, fill, rand,uni_tensor, range_a,range_b,range_c = sess.run([a,b,c, b_zero,c_zero, all_one,all_one_like, fill, rand,uni_tensor, range_a,range_b,range_c])
    print("a: ", a)
    print("b: ", b)
    print("c: ", c) 
    #
    print("b_zero: ", b_zero)
    print("c_zero: ", c_zero)
    #
    print("all_one: ", all_one)
    print("all_one_like: ", all_one_like)
    #
    print("fill: ", fill)
    #
    print("rand: ", rand)
    print("uni_tensor: ", uni_tensor)
    #
    print("range_a: ", range_a)
    print("range_b: ", range_b)
    print("range_c: ", range_c)


a:  [0 0 0 0 0]
b:  [[0 0 0 0 0]
 [0 0 0 0 0]]
c:  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
b_zero:  [[0. 0. 0.]
 [0. 0. 0.]]
c_zero:  [[0 0 0]
 [0 0 0]]
all_one:  [[1 1 1]
 [1 1 1]]
all_one_like:  [[1. 1. 1.]
 [1. 1. 1.]]
fill:  [[6 6 6]
 [6 6 6]]
rand:  [[ 9.047421  14.034974 ]
 [ 7.6613665 11.476557 ]
 [ 9.257022  10.248421 ]]
uni_tensor:  [[0.19178128 0.15840137]
 [0.47626448 0.5821588 ]]
range_a:  [0 1 2 3 4 5 6 7 8 9]
range_b:  [ 3  6  9 12 15]
range_c:  [ 3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5
 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5]


In [12]:
# ref: https://cangmang.xyz/articles/1648196494511
# 索引与切片

import tensorflow as tf
import os

# 索引
image_tensor = tf.random.normal([6, 2, 2, 3])  # 创建尺寸为 (6, 2, 2, 3) 的图片张量
img_1 = image_tensor[0]  # 输出第一张图片
is_equal = image_tensor[5] == image_tensor[-1] # 直接比较为false，但是value是相等的
img_01 = image_tensor[0][1]
is_euql_2 = image_tensor[0][1] == image_tensor[0, 1]

# 切片
img_24 = image_tensor[1:4] #(idx=1,2,3) 3张图片
is_euqal_3 = image_tensor[1, ::] == image_tensor[1]
chl_3 = image_tensor[:, :, :, 2] # 输出第三个通道的所有像素
img_22 = image_tensor[:2, ..., 1:]  # 输出前两张图片中的绿色和蓝色通道 (省略号表示全部包含)

with tf.Session() as sess:
    image_tensor,img_1,img_01, img_24,chl_3,img_22 = sess.run([image_tensor,img_1,img_01, img_24,chl_3,img_22])
    print("image_tensor: ", image_tensor)
    print("img_1: ", img_1)
    print("is_equal: ", is_equal)
    print("img_01: ", img_01)
    print("is_euql_2: ", is_euql_2)
    print("================")
    # print("img_24: ", img_24)
    print("is_euqal_3: ", is_euqal_3)
    print("chl_3: ", chl_3)
    print("img_22: ", img_22)

image_tensor:  [[[[ 0.11219636 -1.5841174   1.1320088 ]
   [-1.5522788  -1.5173947  -0.12243319]]

  [[ 0.3022998  -1.0721402   1.4884635 ]
   [ 1.1760614   1.1659884   0.34441862]]]


 [[[-1.4548928   0.8258269  -1.5944623 ]
   [ 0.2254311  -1.0259813  -0.78621215]]

  [[ 0.7828725  -0.98339516  0.292563  ]
   [ 0.04303534  1.9668304   0.38038474]]]


 [[[-0.95007885 -0.3697357  -0.10575559]
   [ 1.225607   -0.46089908  0.95813596]]

  [[-2.486247    0.7239574   1.6637106 ]
   [ 0.37496284  0.6989193   0.54659605]]]


 [[[-0.38194653  0.6619156   0.88719743]
   [ 1.4638202   1.8973582   0.64426035]]

  [[ 0.29549518  0.87561435  0.8641024 ]
   [ 0.7484896  -0.26386473  1.3528152 ]]]


 [[[ 2.2938144  -0.25775045 -0.01630264]
   [-1.4078705  -0.00353291  0.23458996]]

  [[-0.07025912 -0.4988201   1.4642631 ]
   [-0.09649902 -0.5315423   0.49879175]]]


 [[[ 1.6557034  -0.02650904 -0.98220646]
   [ 0.37473494 -0.90853775 -1.2972848 ]]

  [[ 0.6705577   2.0807226   0.36097088]
   [ 0.756

In [29]:
# ref: https://cangmang.xyz/articles/dimension-scaling-and-swapping-of-tensors#%E5%BC%A0%E9%87%8F%E7%9A%84%E7%BB%B4%E5%BA%A6%E4%BC%B8%E7%BC%A9%E4%B8%8E%E4%BA%A4%E6%8D%A2
import tensorflow as tf 

# tensor的维度伸缩和交换
a = tf.random.normal([5, 20, 7]) #  构建三维张量，维度为 5*20*7
# 增维：tf.expand_dims()
a2 = tf.expand_dims(a, axis=0) # 在第 0 维上添加一个维度 => [1, 5, 20, 7]
# 降维：tf.squeeze()
a3 = tf.squeeze(a2, axis=0) # 删除第 0 维

# 张量的合并、分割与复制
#
b = tf.random.normal([1, 5, 20, 7])
#
# tensor合并: tf.concat() (不增加维度，但是会扩大axis指定维度的值，并且要求其他轴必须完全相同)
c = tf.concat([a2, b], axis=0) # 在第 0 维度上合并
c2 = tf.concat([a2, b], axis=1) # 在第 1 维度上合并
# tensor合并: tf.stack() (增加维度，并且要求其他轴必须完全相同)
d = tf.stack([a2, b], axis=0) # 在第 0 维度上合并
d2 = tf.stack([a2, b], axis=1) # 在第 1 维度上合并
#
# tensor分割
scores = tf.random.normal([5, 3, 2])
result = tf.split(scores, num_or_size_splits=5) # 将张量等分为 5 份
result_2 = tf.split(scores, num_or_size_splits=[1, 2, 2], axis=0) # 将张量等分为 1 份，2 份，2 份

with tf.Session() as sess:
    # a, = sess.run([a])
    print("a shape: ", a.shape) # 输出张量的形状
    print("a2 shape: ", a2.shape) # 输出张量的形状
    print("a3 shape: ", a3.shape)
    print("c shape: ", c.shape)
    print("c2 shape: ", c2.shape)
    print("d shape: ", d.shape)
    print("d2 shape: ", d2.shape)
    print("result: ", result) # 返回一个长度为5的list, (1,3,2)
    print("result_2: ", result_2) # 返回一个长度为3的list, [(1,3,2), (2,3,2), (2,3,2)]

a shape:  (5, 20, 7)
a2 shape:  (1, 5, 20, 7)
a3 shape:  (5, 20, 7)
c shape:  (2, 5, 20, 7)
c2 shape:  (1, 10, 20, 7)
d shape:  (2, 1, 5, 20, 7)
d2 shape:  (1, 2, 5, 20, 7)
result:  [<tf.Tensor 'split_2:0' shape=(1, 3, 2) dtype=float32>, <tf.Tensor 'split_2:1' shape=(1, 3, 2) dtype=float32>, <tf.Tensor 'split_2:2' shape=(1, 3, 2) dtype=float32>, <tf.Tensor 'split_2:3' shape=(1, 3, 2) dtype=float32>, <tf.Tensor 'split_2:4' shape=(1, 3, 2) dtype=float32>]
result_2:  [<tf.Tensor 'split_3:0' shape=(1, 3, 2) dtype=float32>, <tf.Tensor 'split_3:1' shape=(2, 3, 2) dtype=float32>, <tf.Tensor 'split_3:2' shape=(2, 3, 2) dtype=float32>]
